#!/usr/bin/env python3
"""Assign pubDates to the Aurum SME cluster: one post per weekday, in `seq` order.

Dry run (prints the plan, changes nothing):
    python3 context/aurum/batches/2026-09-30-wave-3/tools/reschedule.py --start 2026-10-01

Apply (writes calendar.json, CALENDAR.md and the pubDate line of every MDX that exists):
    python3 context/aurum/batches/2026-09-30-wave-3/tools/reschedule.py --start 2026-10-01 --apply

Rules:
- Slots are Monday to Friday, starting at --start (moved to the next weekday if needed).
- Holidays in HOLIDAYS are skipped (override with --skip YYYY-MM-DD,...).
- Order is calendar.json `seq`. Never reorder here; body links rely on it.
- Only the `pubDate:` frontmatter line is touched. Files that do not exist yet are skipped
  (writers create them later with the date from calendar.json).
- Idempotent: running it twice with the same --start changes nothing the second time.
"""
import argparse, datetime as dt, json, re, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PLAN = HERE.parent
REPO = HERE.parents[4]
CAL = PLAN / "calendar.json"
HOLIDAYS = ["2026-12-24", "2026-12-25", "2026-12-31", "2027-01-01"]


def slots(start, n, skip):
    d, out = start, []
    while len(out) < n:
        if d.weekday() < 5 and d.isoformat() not in skip:
            out.append(d)
        d += dt.timedelta(days=1)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--start", required=True, help="first publication day, YYYY-MM-DD")
    ap.add_argument("--skip", default=",".join(HOLIDAYS), help="comma-separated days to skip")
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()
    start = dt.date.fromisoformat(a.start)
    skip = {s.strip() for s in a.skip.split(",") if s.strip()}
    cal = json.load(open(CAL, encoding="utf-8"))
    cal.sort(key=lambda c: c["seq"])
    days = slots(start, len(cal), skip)
    changes = []
    for c, d in zip(cal, days):
        new = d.isoformat()
        if c.get("pubDate") != new:
            changes.append((c["seq"], c["translationKey"], c.get("pubDate"), new))
        c["pubDate"] = new
    first3 = [c for c in cal if c["wave"] == 3][:1]
    print(f"{len(cal)} posts, {days[0]} .. {days[-1]}; first wave-3 post {first3[0]['pubDate'] if first3 else '-'}")
    print(f"{len(changes)} date changes in calendar.json")
    if not a.apply:
        for s, k, o, n in changes[:12]:
            print(f"  seq {s:3} {k}: {o} -> {n}")
        print("dry run: nothing written. Add --apply.")
        return
    json.dump(cal, open(CAL, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    touched, missing = 0, 0
    for c in cal:
        for lang, slug in (("en", c["en_slug"]), ("de", c["de_slug"])):
            f = REPO / "brands" / "aurum" / lang / f"{slug}.mdx"
            if not f.exists():
                missing += 1
                continue
            t = f.read_text(encoding="utf-8")
            t2, n = re.subn(r"^pubDate: .*$", f"pubDate: {c['pubDate']}", t, count=1, flags=re.M)
            if n != 1:
                sys.exit(f"no pubDate line in {f}")
            if t2 != t:
                f.write_text(t2, encoding="utf-8")
                touched += 1
    rows = ["# Aurum SME cluster: publication calendar", "",
            f"Generated by `tools/reschedule.py --start {start}`. One post per weekday, skipped: {', '.join(sorted(skip))}.", "",
            "| seq | pubDate | wave | id | funnel | DE slug | EN slug | status |",
            "|---:|---|---:|---|---|---|---|---|"]
    for c in cal:
        rows.append(f"| {c['seq']} | {c['pubDate']} | {c['wave']} | {c['id']} | {c['funnelStage']} | `{c['de_slug']}` | `{c['en_slug']}` | {c['status']} |")
    (PLAN / "CALENDAR.md").write_text("\n".join(rows) + "\n", encoding="utf-8")
    print(f"MDX files updated: {touched}; not yet written (skipped): {missing}; CALENDAR.md written")


if __name__ == "__main__":
    main()
